/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Geomini", "SF Pro Text", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        display: ["Geomini", "SF Pro Display", "SF Pro Text", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "SF Mono", "Menlo", "monospace"],
      },
      fontSize: {
        'hero': ['56px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '700' }],
        'page-title': ['40px', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
        'section-title': ['28px', { lineHeight: '1.2', letterSpacing: '-0.015em', fontWeight: '600' }],
        'card-title': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.7', fontWeight: '400' }],
        'body': ['16px', { lineHeight: '1.7', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'caption': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'label': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      colors: {
        velness: {
          purple: {
            50: '#F6F3FF',
            100: '#EDE9FE',
            200: '#DDD6FE',
            300: '#C9A8F0',
            400: '#A878E0',
            500: '#8A5FC7',
            600: '#7A4FB8',
            700: '#6A3FA8',
            800: '#5A2F98',
            900: '#4A1F88',
          },
          cyan: {
            50: '#ECFEFF',
            100: '#CFFAFE',
            200: '#A5F3FC',
            300: '#67E8F9',
            400: '#22D3EE',
            500: '#06B6D4',
            600: '#0891B2',
            700: '#0E7490',
            800: '#155E75',
            900: '#164E63',
          },
           glass: {
             highlight: 'var(--glass-highlight)',
             light: 'var(--glass-light)',
             medium: 'var(--glass-medium)',
             strong: 'var(--glass-strong)',
             tint: 'var(--glass-tint)',
             dark: 'var(--glass-dark)',
             border: 'var(--glass-border)',
           },
        },
        background: {
          primary: 'var(--background-primary)',
          secondary: 'var(--background-secondary)',
          tertiary: 'var(--background-tertiary)',
          elevated: 'var(--background-elevated)',
        },
        surface: {
          primary: 'var(--surface-primary)',
          secondary: 'var(--surface-secondary)',
          tertiary: 'var(--surface-tertiary)',
          card: 'var(--surface-card)',
          elevated: 'var(--surface-elevated)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          inverse: 'var(--text-inverse)',
          disabled: 'var(--text-disabled)',
          muted: 'var(--text-muted)',
        },
        border: {
          default: 'var(--border-default)',
          strong: 'var(--border-strong)',
          subtle: 'var(--border-subtle)',
          focus: 'var(--border-focus)',
        },
        brand: {
          primary: 'var(--brand-primary)',
          primaryDeep: 'var(--brand-primaryDeep)',
          secondary: 'var(--brand-secondary)',
          tertiary: 'var(--brand-tertiary)',
          onPrimary: 'var(--brand-onPrimary)',
          contrastText: 'var(--brand-contrastText)',
          subtle: 'var(--brand-subtle)',
          border: 'var(--brand-border)',
        },
        overlay: {
          light: 'var(--overlay-light)',
          medium: 'var(--overlay-medium)',
          strong: 'var(--overlay-strong)',
          backdrop: 'var(--overlay-backdrop)',
        },
        success: 'var(--success)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        info: 'var(--info)',
      },
      backgroundColor: {
        'app-dark': '#1A1327',
        'app-light': '#F6F3FF',
      },
      borderRadius: {
        'glass': '16px',
        'glass-sm': '12px',
        'glass-lg': '24px',
      },
      spacing: {
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
      },
    },
  },
  plugins: [],
}
